export const socketConstants = {
  connectionUrl: "https://polling-backend-ts7f.onrender.com/",
  oldConnection: "old-connection",
  createStudent: "create-student",
  createTeacher: "create-teacher",
  connectionId: "connection-id",
  validConnection: "valid-connection",
  alreadyExists: "already-exists",
  questionPublish: "question-publish",
  questionPost: "post-question",
  answerPublish: "answer-publish",
  getResult: "get-result",
  resultPublish: "result-publish",
  getOnlineStudents: "get-online-students",
  onlineStudents: "online-students",
  closeConnection: "close-connection",
  triggerClose: "trigger-close",
  getPollingHistory: "get-polling-history",
  pollingHistory: "polling-history",
  settingNewQuestion: "setting-new-question",
  newQuestionInbound: "new-question-inbound",
};
